

---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: ingress-nginx
  namespace: kubocd
spec:
  description: The Ingress controller
  protected: true
  package:
    repository: quay.io/kubosa/packages/ingress-nginx
    tag: 4.12.1-p02
    interval: 30m
  targetNamespace: ingress-nginx
  createNamespace: true
  parameters:
    deployInControlPlane: true

