---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: kubauth-kubeconfig
  namespace: kubocd
spec:
  description: Kubeconfig info server
  protected: false
  package:
    repository: quay.io/kubosa/packages/kubauth-kubeconfig
    tag: 0.1.0-p02
    interval: 30m
  targetNamespace: kubauth
  createNamespace: true
  specPatchByModule:
    noname:
      values:
        server:
          dumpExchanges: 0
        image:
          pullPolicy: Always
          #tag: 0.1.0-snapshot-ubuntu
  parameters:
    #deployInControlPlane: true
    deployInControlPlane: false
    tolerations:
      - key: node-role.kubernetes.io
        operator: "Equal"
        effect: NoSchedule
        value: services
    nodeSelector:
      node-role.kubernetes.io: "services"

    logger:
      level: debug
      mode: text
